Fix error terminal doesn't show output on Windows
When debug python on Windows OS, the terminal don't show output (by python print() command) cause of the error below:

Traceback (most recent call last):
  File "C:\Portable Apps\Sublime Text\Data\Packages\Debugger\modules\debugger\terminal.py", line 30, in _read
    line = self.process.read().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'